### ISSUE TITLE
IsCyclic

### ISSUE THREAD

**Issue by joshmaglione** [thetensor-space/TensorSpace#17]
Does IsCyclic only work over finite fields? With the following code, I get an error.

```
A := MatrixAlgebra(Rationals(), 4);
R<x> := PolynomialRing(Rationals());
F := sub< A | A!1, CompanionMatrix(x^4-x^2-2) >;
F;
IsCyclic(F);
```

Error output:
```
IsCyclic(
    R: Matrix Algebra of degree 4 and dimension 4 with 2 generators...
)
__IsCyclic(
    R: Matrix Algebra of degree 4 and dimension 4 with 2 generators...
)
In file "./eMAGma/src/Util/ConjugateCyclic.m", line 
425, column 29:
>>          if exists (s){ t : t in S | Degree (MinimalPolynomial (t)) eq dS
                               ^
Runtime error in for: Iteration is not possible over this object
```

**Comment by galois60** [comment]
I just saw this error report and ran it myself. It was not until I was in the weeds that I saw you had applied it to an algebra defined over the rationals. The correct generality of our various matrix algebra functions is a good one to keep in mind––especially now, as we're starting to collect them together more systematically into a coherent whole––but I confess that I wrote this particular function only with finite fields in mind. This bug occurs because I try to iterate over a set that would be infinite here! I probably don't need to do that, but as I say it was intended only for finite fields.
